language: python
python:
    - "2.7"
install: 
    - pip install -q -U pip setuptools tox coveralls
    #"python setup.py develop"
script:
    tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
